application: djd-memc
version: 1
runtime: go
api_version: go1

instance_class: F4_1G

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 970
  max_concurrent_requests: 20

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: _go_app
